# Start from the latest Alpine image
FROM python:3.10-alpine

RUN apk update \
    && apk add --no-cache python3-dev build-base

# Set the working directory
WORKDIR /app

COPY . /app

# Create and activate a virtual environment
RUN python3 -m venv /app/venv

# Upgrade pip and setuptools 
RUN /app/venv/bin/pip install --upgrade pip setuptools


RUN /app/venv/bin/pip install --no-cache-dir -r requirements.txt

# Set the entry point to use the virtual environment's Python interpreter
CMD ["/app/venv/bin/python", "app.py"]


